/*
** EPITECH PROJECT, 2017
** for_norme
** File description:
** music.c
*/

#include <stdbool.h>
#include "prototype.h"
#include "piano.h"

/*music*/
/**
 * 0 : elfen lied
 * 1 : steins gate
 * 2 : blue bird
 * 3 : unravel
 * 4 : bleach
 */

const char *music_g[] =
{
	"ISOppISOpapIOuyuIyTyuIOpapOISOppISOpapIOuyuIyTyapOIiYiIPaSdpOdSfpSapOiyTPaSdpOdSfpSspOIpaOISOppISOpapIOuyuIyTyuIOpapOISOppISOpapIOuyuIyTyapOIYiIpaSadSapOpaSDaSpaSpadSaSpOuIOpSfDaSGfdSDaSpOuIOpSfDaSPaSdpOdSfpSapOiyTPaSdpOdSfpSspOIpaOISOppISOpapIOuyuIyTyuIOpapOISOppISOpapIOuyuIyTyapOIYiI",
	"woPDyoPdyoPSyoPdyoPwpDyopdyopSyopdyopqoODtoOdtoOstoOdtoO9iseioseiowiadyiaqrygDdswDZypPwdzypPwSLypPwdzypPwhjZTopwdHzTopwdHLTopwSHzTopqDHltoOsghWuosfl8wPJqOhtYI4wWt84i8wWi48wWiti8owEt8wEotoOqWEOPOowEoDs48wWEt10wE4wti8wWt48wWitiwEot8wEtoOPqWYsOTowtYioEi4wWtwWu4eti81tiptYPTisTiPiUDYOsToPoO1tYP8tYOwoPD4EYo8tYOwWwTisTiPiPDIsgQEIPDHWths4qWYTtw15EwTisTiPiPDYOkToPoO1tYP8tYOwoPD4EYo8tYOwWwTiPqOsEPStsDTIPgTOTtiPgE9PDJ4PsgJqEtqw4psDj8eqetwoPDyoPdyoPSyoPdyoPwpDyopdyopSyopdyopqoODtoOdtoOstoOdtoO9iseioseiowiadyiaqrygDdswDZypPwdzypPwSLypPwdzypPwThjZTopwdHzTopwdHLTopwSHzTopQDGZtIOQdjztIOQSGLtIOQjzbwvylpzPjwJyhpjPl9gefupid9seoupi6b0zrxtk6l0jrktf0hrGIdof0ardIpo7nQxTCyL7zQkTLyj9hegufid9sefupidqHtdogOHQltgoHOzqHtlocOHQltcoHOV8BJwBJEBJoBJ8BJwBJEBJTBJtBJTBJEBJtBJWBJEBJwBJWBJ4i8wWt48wWiti8owEt8wEotoOqWEOPOowEoDs48wWEt10wE4wti8wWi48wWiai8oywEot8wEtoOPqWYgTOowtYiEOi4wWtwWY4eti81tiptYPTOsSglJZYHlPshJhHtsDJoHhHZisPhPisDHoOoTSglOSgJgJZYGlcIUGJZVOsvlitEiODWS8Yos1tYPoYTisTiPiPDYOsToPoO1tYP8tYOwoPD4EYOwWwTiPqOsEPStsPTIPgTOTtiPgEPDJ4PsgJqEtqw4psDj8eEupDTisTiPtPDYOgToPoO1tYP8tYOwoPD4EYo8tYOwWwTisWTiPiPDTsgQEIPDHWths4qWYT1wt5EWTisTiPiPDYOsToPoO1tYP8tYOwoPD4EYo8tYOwWwTiPqOsEPStsDTIPgTOTtiPgEPDJ4PsgJqEtqw4psDj8eEipDglLcBDiglZbqtwoPDyoPSyoPdyoPwpDyopdyopSyopdyopqoODtoOdtoOstoOdtoO9iseioseiowiadyiaqrygDdswdZypPwdzypPwSLypPwdzypPwhjZTopwdHzTopwdhLTopqDHltoOsghWuosfl8wPJqOshtYo4wWt",
	"upasapupasdsdfupasappfdpfdooppupasusapoptyuuuuiopoooopasaupasusapoptyuuuuisapooppupassasaaasddsappsdfpsdffhgfupasapupasdsdfupasappfdpfdooppupasapupasdsdfupasappfdpfdoopppfdpfdoopppfdpfdooppupasusapoptyuuuuiopoooopasaupasusapooptyuuuuisapooppupassasaaasddsappsdfpsdffhgfupasapupasdsdfupasappfdpfdooppupasapupassdsdfupasappfdpfdoopppfppoppfppopsspsddadsfffssdfupasapupasdsdfupasappfdpfdooppupasapupasdsdfupasappfdpfdoopppfdpfdoopppfdpfdoopp",
	"lJjhlJjhhggDgdyyyyddPpppPPjjJJPsPposlPJpjohohigigYDigydydydydyddzdzPJpjpjpjPJPJigigydydydtsydydigigydydydtsydydigigydydydtsydydydoyddzslsldzslslslPJpjPJpjigigdzslslslPJpjpjPJgcPJPJhvgcfxPJpjPJpjohpjPJ",
	"pflkzlkjpflkzlkjislkzlkjislkzlkjodlkzlkjodlkzlkjpflkzlkjpflkzlkjeusadsapeusadsapqtsadsapqtsadsapwysadsapwysadsapeusadsapeusadsapeusadsapeusadsapqtsadsapqtsadsapwysadsapwysadsapeusadsapeusadsapeusadsapeusadsapeuslakzdslakjpeuslakzdslakjpeuslakzdslakjpeuslakzdslakjpqtslakzdslakjpqtslakzdslakjpwyslakzdslakjpwyslakzdslakjppflkzlkjpflkzlkjislkzlkjislkzlkjodlkzlkjodlkzlkjpflkzlkjpflkzlkjeusadsapeusadsapqtsadsapqtsadsapwysadsapwysadsapeusadsapeusadsapeusadsapeusadsapqtsadsapqtsadsapwysadsapwysadsapeusadsapeusadsapeusadsapeusadsapeuslakzdslakjpeuslakzdslakjpeuslakzdslakjpeuslakzdslakjpqtslakzdslakjpqtslakzdslakjpwyslakzdslakjpwyslakzdslakjp",
	NULL
};
